name = "rugcheck-backend"
main = "src/index.ts"
compatibility_date = "2025-04-06"
compatibility_flags = ["nodejs_compat"]

[env.production]
[env.production.vars]
DATABASE_URL = "prisma+postgres://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiZTMzZGJiMDQtZGRmMi00ZTc4LWExZGEtYmJjODc2OTU3ZTQ5IiwidGVuYW50X2lkIjoiZjNkMmNlNGZjZjk2NTgwMTczNDdiMTUwYjUzMWVlOGUyNzNkZmJkNjY0NGYzNTlmZGZhMzJiN2VkMDQ3N2ZiZSIsImludGVybmFsX3NlY3JldCI6IjU3ZTRiOTE2LTQ4YjgtNDkxYy05MGM2LWI2MWZiMWZiYTNmMiJ9.t8ybWXAC1CQwJJLWhzF5cuEFzewN_gGWWGLlyFv3HZ4"
# DATABASE_URL = "postgres://postgres:password@localhost:5432/postgres"
REDIS_HOST = "localhost" # Use local Redis for dev
REDIS_PORT = "6379"
REDIS_PASSWORD = ""      # Leave blank if no password


[triggers]
crons = ["*/1 * * * *"] # Every 1 minutes
